INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000022', '관리자메인', '/adminmain/**', '관리자메인', 'url', '1', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000022', SYSDATE);
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000013', '관리자메인', '\A/adminmain/.*\Z', '관리자메인', 'url', '1', SYSDATE);
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000013', SYSDATE);
