CREATE TABLE COMTNINSTTINFO (
    INSTT_ID CHAR(20) NOT NULL,
    INSTT_NM VARCHAR(100) NOT NULL,
    REPRSNT_NM VARCHAR(50) NULL,
    BIZRNO VARCHAR(20) NULL,
    ZIP VARCHAR(6) NULL,
    ADRES VARCHAR(200) NULL,
    DETAIL_ADRES VARCHAR(200) NULL,
    BIZ_REG_FILE_PATH VARCHAR(500) NULL,
    INSTT_STTUS CHAR(1) DEFAULT 'P' NULL,
    FRST_REGIST_PNTTM DATETIME DEFAULT SYSDATETIME NULL,
    LAST_UPDT_PNTTM DATETIME DEFAULT SYSDATETIME NULL,
    PRIMARY KEY (INSTT_ID)
);
