services:
  carbosys-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_HOME: "${APP_HOME:-/opt/app}"
    restart: unless-stopped
    environment:
      APP_HOME: "${APP_HOME:-/opt/app}"
      EUREKA_XMS: "64m"
      EUREKA_XMX: "128m"
      CONFIG_XMS: "64m"
      CONFIG_XMX: "128m"
      GATEWAY_XMS: "128m"
      GATEWAY_XMX: "256m"
      EGOV_HOME_XMS: "256m"
      EGOV_HOME_XMX: "512m"
      CUBRID_HOST: "host.docker.internal"
    ports:
      - "8761:8761"
      - "9000:9000"
    container_name: carbosys-app
    hostname: carbosys-app
    networks:
      - carbosys-net
    volumes:
      - "./module:${APP_HOME:-/opt/app}/module"
      - "./logs:${APP_HOME:-/opt/app}/logs"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --url http://carbosys-app:9000
    networks:
      - carbosys-net

networks:
  carbosys-net:
    driver: bridge
