<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>egovframework</groupId>
	<artifactId>ncc</artifactId>
	<version>4.3.0</version>
	<packaging>pom</packaging>
	<name>ncc</name>

	<modules>
		<module>module/ConfigServer</module>
		<module>module/EgovAuthor</module>
		<module>module/EgovBoard</module>
		<module>module/EgovCmmnCode</module>
		<module>module/EgovLogin</module>
		<module>module/EgovLoginPolicy</module>
		<module>module/EgovSR</module>
		<module>module/EgovMain</module>
		<module>module/EgovHome</module>
		<module>module/EgovMobileId</module>
		<module>module/EgovQuestionnaire</module>
		<module>module/EgovSearch</module>
		<module>module/EgovMsaManager</module>
		<module>module/EurekaServer</module>
		<module>module/GatewayServer</module>
	</modules>

</project>
