DELETE FROM COMTNAUTHORROLERELATE WHERE ROLE_CODE='web-000013';
DELETE FROM COMTNROLEINFO WHERE ROLE_CODE='web-000013';
DELETE FROM COMTNAUTHORROLERELATE WHERE ROLE_CODE='web-000022';
DELETE FROM COMTNROLEINFO WHERE ROLE_CODE='web-000022';
