-- 그룹
INSERT INTO MSATNAUTHORGROUPINFO (GROUP_ID, GROUP_NM, GROUP_CREAT_DE,GROUP_DC) VALUES ('GROUP_00000000000000', '0번  그룹입니다',  SYSDATE(), '0번  그룹입니다');

-- 권한정보
INSERT INTO MSATNAUTHORINFO VALUES ('ROLE_ANONYMOUS' ,'모든 사용자', '', NOW());
INSERT INTO MSATNAUTHORINFO VALUES ('IS_AUTHENTICATED_ANONYMOUSLY', '스프링시큐리티 내부사용(롤부여 금지)', '', NOW());
INSERT INTO MSATNAUTHORINFO VALUES ('IS_AUTHENTICATED_REMEMBERED', '스프링시큐리티 내부사용(롤부여 금지)', '', NOW());
INSERT INTO MSATNAUTHORINFO VALUES ('IS_AUTHENTICATED_FULLY', '스프링시큐리티 내부사용(롤부여 금지)', '', NOW());
INSERT INTO MSATNAUTHORINFO VALUES ('ROLE_USER', '일반 사용자', '', NOW());
INSERT INTO MSATNAUTHORINFO VALUES ('ROLE_ADMIN', '관리자', '', NOW());

-- 롤 등록
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000001', '로그인', '/uat/uia/**', '로그인', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000002', '로그인정책관리', '/uat/uap/**', '로그인정책관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000003', '권한관리', '/sec/ram/**', '권한관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000004', '권한그룹관리', '/sec/rgm/**', '권한그룹관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000005', '그룹관리', '/sec/gmt/**', '그룹관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000006', '롤관리', '/sec/rmt/**', '롤관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000007', '모바일신분증', '/mip/**', '모바일신분증', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000008', '블로그관리', '/cop/bls/**', '블로그관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000009', '게시판관리', '/cop/bbs/**', '게시판관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000010', '게시글관리', '/cop/brd/**', '게시글관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000011', '커뮤니티관리', '/cop/cmy/**', '커뮤니티관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000012', '설문관리', '/uss/olp/qmc/**', '설문관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000013', '설문조사','/uss/olp/qri/**','설문조사', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000014', '설문템플릿관리','/uss/olp/qtm/**','설문템플릿관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000015', '응답자관리','/uss/olp/qrm/**','응답자관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000016', '질문관리','/uss/olp/qqm/**','질문관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000017', '항목관리','/uss/olp/qim/**','항목관리', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000018', '공통분류코드','/sym/ccm/ccc/**','공통분류코드', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000019', '공통상세코드','/sym/ccm/cde/**','공통상세코드', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000020', '공통코드','/sym/ccm/cca/**','공통코드', 'url', '1', SYSDATE());
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000021', '검색엔진','/ext/ops/**','검색엔진', 'url', '1', SYSDATE());

-- 권한 롤 매핑
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ANONYMOUS', 'web-000001', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000002', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000003', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000004', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000005', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000006', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000007', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000008', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000009', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000010', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000011', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000012', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000013', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000014', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000015', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000016', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000017', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000018', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000019', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000020', SYSDATE());
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000021', SYSDATE());


-- 롤 계층구조
INSERT INTO MSATNROLES_HIERARCHY VALUES ('ROLE_ANONYMOUS', 'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO MSATNROLES_HIERARCHY VALUES ('IS_AUTHENTICATED_ANONYMOUSLY', 'IS_AUTHENTICATED_REMEMBERED');
INSERT INTO MSATNROLES_HIERARCHY VALUES ('IS_AUTHENTICATED_REMEMBERED', 'IS_AUTHENTICATED_FULLY');
INSERT INTO MSATNROLES_HIERARCHY VALUES ('IS_AUTHENTICATED_FULLY', 'ROLE_USER');
INSERT INTO MSATNROLES_HIERARCHY VALUES ('ROLE_USER', 'ROLE_ADMIN');

-- 사용자보안설정
INSERT INTO MSATNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE) VALUES ('USRCNFRM_00000000000', 'USR03', 'ROLE_ADMIN');
INSERT INTO MSATNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE) VALUES ('USRCNFRM_00000000001', 'USR01', 'ROLE_USER');
INSERT INTO MSATNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE) VALUES ('USRCNFRM_00000000002', 'USR02', 'ROLE_USER');
INSERT INTO MSATNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE) VALUES ('USRCNFRM_99999999999', 'USR03', 'ROLE_ADMIN');