spring:
  messages:
    encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false
  datasource:
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    url: jdbc:cubrid:localhost:33000:com:::?charset=UTF-8
    username: dba
    password: ""
    hikari:
      maximum-pool-size: 20
      connection-timeout: 20000
      idle-timeout: 30000
      minimum-idle: 5
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.CUBRIDDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

token:
  accessSecret: "7FB814B9D7FFB3D675EF1F525C1D61B254227B3B0A771DDDBDFE4112A1F42F66" # sha256(egovframework)
  refreshSecret: "7FB814B9D7FFB3D675EF1F525C1D61B254227B3B0A771DDDBDFE4112A1F42F66" # sha256(egovframework)
  accessExpiration: 7200000 # TTL (millisecond, 2 Hour)
  refreshExpiration: 86400000 # TTL (millisecond, 1 Day)

server:
  forward-headers-strategy: native

logging:
  level:
    org:
      egovframe:
        rte: debug
      springframework:
        boot:
          autoconfigure: error
        web: debug
    egovframework:
      com: debug

