# CUBRID Database Server Configuration File

[%service]
service=server,broker

[%server]
master_port_id=1534
source_env=/opt/carbosys/conf/cubrid.conf

[%client]
source_env=/opt/carbosys/conf/cubrid.conf

[standalone]
source_env=/opt/carbosys/conf/cubrid.conf
