CREATE INDEX [comtnauthorrolerelate_i01] ON [dba].[comtnauthorrolerelate] ([author_code]);
CREATE INDEX [comtnauthorrolerelate_i02] ON [dba].[comtnauthorrolerelate] ([role_code]);
CREATE INDEX [msatnauthorrolerelate_i01] ON [dba].[msatnauthorrolerelate] ([author_code]);
CREATE INDEX [msatnauthorrolerelate_i02] ON [dba].[msatnauthorrolerelate] ([role_code]);
CREATE INDEX [msatnroles_hierarchy_i01] ON [dba].[msatnroles_hierarchy] ([parnts_role]);
CREATE INDEX [msatnroles_hierarchy_i02] ON [dba].[msatnroles_hierarchy] ([chldrn_role]);
CREATE INDEX [msatnemplyrscrtyestbs_i04] ON [dba].[msatnemplyrscrtyestbs] ([author_code]);
CREATE INDEX [msatnmenucreatdtls_i02] ON [dba].[msatnmenucreatdtls] ([menu_no]);
CREATE INDEX [msatnmenucreatdtls_i03] ON [dba].[msatnmenucreatdtls] ([mapng_creat_id]);
CREATE INDEX [msatnmenucreatdtls_i04] ON [dba].[msatnmenucreatdtls] ([author_code]);
CREATE INDEX [comtnfiledetail_i01] ON [dba].[comtnfiledetail] ([atch_file_id]);
CREATE INDEX [comtnmenucreatdtls_i02] ON [dba].[comtnmenucreatdtls] ([menu_no]);
CREATE INDEX [comtnmenucreatdtls_i03] ON [dba].[comtnmenucreatdtls] ([mapng_creat_id]);
CREATE INDEX [comtnmenucreatdtls_i04] ON [dba].[comtnmenucreatdtls] ([author_code]);
CREATE INDEX [comtccmmncode_i01] ON [dba].[comtccmmncode] ([cl_code]);
CREATE INDEX [comtccmmndetailcode_i01] ON [dba].[comtccmmndetailcode] ([code_id]);
CREATE INDEX [comtnbbs_i01] ON [dba].[comtnbbs] ([bbs_id]);
CREATE INDEX [comtncomment_i01] ON [dba].[comtncomment] ([ntt_id], [bbs_id]);
CREATE INDEX [comtnemplyrinfo_i01] ON [dba].[comtnemplyrinfo] ([orgnzt_id]);
CREATE INDEX [comtnemplyrinfo_i02] ON [dba].[comtnemplyrinfo] ([group_id]);
CREATE INDEX [comtnemplyrscrtyestbs_i04] ON [dba].[comtnemplyrscrtyestbs] ([author_code]);
CREATE INDEX [comtnqestnrinfo_i01] ON [dba].[comtnqestnrinfo] ([qustnr_tmplat_id]);
CREATE INDEX [comtnentrprsmber_i01] ON [dba].[comtnentrprsmber] ([group_id]);
CREATE INDEX [idx_comtnentrprsmber_instt_id] ON [dba].[comtnentrprsmber] ([instt_id]);
CREATE INDEX [comtngnrlmber_i01] ON [dba].[comtngnrlmber] ([group_id]);
CREATE INDEX [comtnqustnrqesitm_i02] ON [dba].[comtnqustnrqesitm] ([qestnr_id], [qustnr_tmplat_id]);
CREATE INDEX [comtnqustnriem_i01] ON [dba].[comtnqustnriem] ([qustnr_qesitm_id], [qestnr_id], [qustnr_tmplat_id]);
CREATE INDEX [comtnqustnrrespondinfo_i01] ON [dba].[comtnqustnrrespondinfo] ([qestnr_id], [qustnr_tmplat_id]);
CREATE INDEX [comtnqustnrrspnsresult_i01] ON [dba].[comtnqustnrrspnsresult] ([qestnr_id], [qustnr_qesitm_id], [qustnr_tmplat_id]);
CREATE INDEX [idx_comtnentrprsmberfile_01] ON [dba].[comtnentrprsmberfile] ([entrprs_mber_id]);
CREATE INDEX [idx_comtninsttfile_01] ON [dba].[comtninsttfile] ([instt_id]);

COMMIT WORK;
