<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>egovframework</groupId>
	<artifactId>EgovCertLogin</artifactId>
	<version>1.0.0</version>
	<name>egov-certlogin</name>
	<url>https://www.egovframe.go.kr</url>

	<licenses>
		<license>
			<name>egov-certlogin</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>

	<!-- eGovFramework Boot Parent ?¤ì • -->
	<parent>
		<groupId>org.egovframe.boot</groupId>
		<artifactId>EgovCertLogin</artifactId>
		<version>4.3.0</version>
		<relativePath/>
	</parent>

	<properties>
		<java.version>1.8</java.version>
		<mysql.connector.version>8.0.33</mysql.connector.version>
		<apache.commons.lang3>3.14.0</apache.commons.lang3>
		<apache.commons.io>2.16.1</apache.commons.io>
		<apache.commons.text>1.12.0</apache.commons.text>
		<jwtt.version>0.12.6</jwtt.version>
		<jaxb.version>2.3.1</jaxb.version>
		<lombok.version>1.18.34</lombok.version>
		<com.mysema.maven.plugin.version>1.1.3</com.mysema.maven.plugin.version>
	</properties>

	<repositories>
		<repository>
			<id>mvn2s</id>
			<url>https://repo1.maven.org/maven2/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>egovframe</id>
			<url>https://maven.egovframe.go.kr/maven/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>EgovCertLogin</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>cubrid</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<version>11.2.0.0035</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<version>${jwtt.version}</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<version>${jwtt.version}</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<version>${jwtt.version}</version>
		</dependency>
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<version>${jaxb.version}</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<version>${lombok.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>

		<!-- ?œì??„ë ˆ?„ì›Œ???¤í–‰?˜ê²½ -->
		<dependency>
			<groupId>org.egovframe.rte</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.egovframe.rte</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.egovframe.rte</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.egovframe.rte</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>EgovCertLogin</artifactId>
					<groupId>commons-logging</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.egovframe.rte</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.egovframe.boot</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.egovframe.boot</groupId>
			<artifactId>EgovCertLogin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<version>${apache.commons.lang3}</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<version>${apache.commons.io}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<version>${apache.commons.text}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>EgovCertLogin</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>EgovCertLogin</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>EgovCertLogin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>EgovCertLogin</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.mysema.maven</groupId>
				<artifactId>EgovCertLogin</artifactId>
				<version>${com.mysema.maven.plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>process</goal>
						</goals>
						<configuration>
							<outputDirectory>target/generated-sources/java</outputDirectory>
							<processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
							<options>
								<querydsl.generatedAnnotationClass>javax.annotation.Generated</querydsl.generatedAnnotationClass>
							</options>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>EgovCertLogin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
