services:
  cubrid:
    image: cubrid/cubrid:11.2
    environment:
      TZ: Asia/Seoul
      CUBRID_DB: com
      CUBRID_LOCALE: ko_KR.utf8
      DB_ROOT_PASSWORD: ""
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"
      - "./data:/var/lib/cubrid"
    platform: linux/x86_64
    ports:
      - "33000:33000"
    container_name: cubrid
    hostname: cubrid
    shm_size: '2gb'
    privileged: true
    networks:
      - carbosys-net

networks:
  carbosys-net:
    name: carbosys-net
    external: true
