CREATE TABLE MSATNAUTHORGROUPINFO (
	GROUP_ID              CHAR(20) NOT NULL,
	GROUP_NM              VARCHAR(60) NOT NULL,
	GROUP_CREAT_DE        CHAR(20) NOT NULL,
	GROUP_DC              VARCHAR(100) NULL,
	PRIMARY KEY (GROUP_ID)
);

CREATE UNIQUE INDEX MSATNAUTHORGROUPINFO_PK ON MSATNAUTHORGROUPINFO (GROUP_ID);

CREATE TABLE MSATNAUTHORINFO (
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	AUTHOR_NM             VARCHAR(60) NOT NULL,
	AUTHOR_DC             VARCHAR(200) NULL,
	AUTHOR_CREAT_DE       CHAR(20) NOT NULL,
	PRIMARY KEY (AUTHOR_CODE)
);

CREATE UNIQUE INDEX MSATNAUTHORINFO_PK ON MSATNAUTHORINFO (AUTHOR_CODE);

CREATE TABLE MSATNROLEINFO (
    ROLE_CODE             VARCHAR(50) NOT NULL,
    ROLE_NM               VARCHAR(60) NOT NULL,
    ROLE_PTTRN            VARCHAR(300) NULL,
    ROLE_DC               VARCHAR(200) NULL,
    ROLE_TY               VARCHAR(80) NULL,
    ROLE_SORT             VARCHAR(10) NULL,
    ROLE_CREAT_DE         CHAR(20) NOT NULL,
    PRIMARY KEY (ROLE_CODE)
);

CREATE UNIQUE INDEX MSATNROLEINFO_PK ON MSATNROLEINFO (ROLE_CODE);

CREATE TABLE MSATNAUTHORROLERELATE (
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	ROLE_CODE             VARCHAR(50) NOT NULL,
	CREAT_DT              DATETIME NULL,
	PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
	FOREIGN KEY MSATNAUTHORROLERELATE_FK1 (AUTHOR_CODE) REFERENCES MSATNAUTHORINFO(AUTHOR_CODE) ON DELETE CASCADE,
	FOREIGN KEY MSATNAUTHORROLERELATE_FK2 (ROLE_CODE) REFERENCES MSATNROLEINFO(ROLE_CODE) ON DELETE CASCADE
);

CREATE UNIQUE INDEX MSATNAUTHORROLERELATE_PK ON MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE);

CREATE INDEX MSATNAUTHORROLERELATE_i01 ON MSATNAUTHORROLERELATE (AUTHOR_CODE);

CREATE INDEX MSATNAUTHORROLERELATE_i02 ON MSATNAUTHORROLERELATE (ROLE_CODE);

CREATE TABLE MSATNROLES_HIERARCHY (
	PARNTS_ROLE           VARCHAR(30) NOT NULL,
	CHLDRN_ROLE           VARCHAR(30) NOT NULL,
	PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
	FOREIGN KEY MSATNROLES_HIERARCHY_FK1 (PARNTS_ROLE) REFERENCES MSATNAUTHORINFO(AUTHOR_CODE) ON DELETE CASCADE,
	FOREIGN KEY MSATNROLES_HIERARCHY_FK2 (CHLDRN_ROLE) REFERENCES MSATNAUTHORINFO(AUTHOR_CODE) ON DELETE CASCADE
);

CREATE UNIQUE INDEX MSATNROLES_HIERARCHY_PK ON MSATNROLES_HIERARCHY (PARNTS_ROLE, CHLDRN_ROLE);

CREATE INDEX MSATNROLES_HIERARCHY_i01 ON MSATNROLES_HIERARCHY (PARNTS_ROLE);

CREATE INDEX MSATNROLES_HIERARCHY_i02 ON MSATNROLES_HIERARCHY (CHLDRN_ROLE);

CREATE TABLE MSATNEMPLYRSCRTYESTBS (
	SCRTY_DTRMN_TRGET_ID  VARCHAR(20) NOT NULL,
	MBER_TY_CODE          CHAR(5) NULL,
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	PRIMARY KEY (SCRTY_DTRMN_TRGET_ID)
);

CREATE UNIQUE INDEX MSATNEMPLYRSCRTYESTBS_PK ON MSATNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID);

CREATE INDEX MSATNEMPLYRSCRTYESTBS_i04 ON MSATNEMPLYRSCRTYESTBS (AUTHOR_CODE);

CREATE TABLE MSATNMENUCREATDTLS (
	MENU_NO               NUMERIC(20) NOT NULL,
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	MAPNG_CREAT_ID        VARCHAR(30) NULL,
	PRIMARY KEY (MENU_NO,AUTHOR_CODE),
	FOREIGN KEY MSATNMENUCREATDTLS_FK1 (AUTHOR_CODE) REFERENCES MSATNAUTHORINFO(AUTHOR_CODE)
);

CREATE UNIQUE INDEX MSATNMENUCREATDTLS_PK ON MSATNMENUCREATDTLS (MENU_NO, AUTHOR_CODE);

CREATE INDEX MSATNMENUCREATDTLS_i02 ON MSATNMENUCREATDTLS (MENU_NO);

CREATE INDEX MSATNMENUCREATDTLS_i03 ON MSATNMENUCREATDTLS (MAPNG_CREAT_ID);

CREATE INDEX MSATNMENUCREATDTLS_i04 ON MSATNMENUCREATDTLS (AUTHOR_CODE);
