ALTER CLASS COMTNENTRPRSMBER ADD ATTRIBUTE INSTT_ID VARCHAR(20);

CREATE INDEX IDX_COMTNENTRPRSMBER_INSTT_ID ON COMTNENTRPRSMBER (INSTT_ID);

UPDATE COMTNENTRPRSMBER M
SET INSTT_ID = (
    SELECT MIN(I.INSTT_ID)
    FROM COMTNINSTTINFO I
    WHERE I.BIZRNO = M.BIZRNO
)
WHERE (M.INSTT_ID IS NULL OR TRIM(M.INSTT_ID) = '')
  AND EXISTS (
      SELECT 1
      FROM COMTNINSTTINFO I
      WHERE I.BIZRNO = M.BIZRNO
  );
