UPDATE COMTNENTRPRSMBER M
SET CMPNY_NM = (
    SELECT I.INSTT_NM
    FROM COMTNINSTTINFO I
    WHERE I.INSTT_ID = M.INSTT_ID
)
WHERE (M.CMPNY_NM IS NULL OR TRIM(M.CMPNY_NM) = '')
  AND EXISTS (
      SELECT 1
      FROM COMTNINSTTINFO I
      WHERE I.INSTT_ID = M.INSTT_ID
        AND I.INSTT_NM IS NOT NULL
        AND TRIM(I.INSTT_NM) <> ''
  );

UPDATE COMTNENTRPRSMBER M
SET CXFC = (
    SELECT I.REPRSNT_NM
    FROM COMTNINSTTINFO I
    WHERE I.INSTT_ID = M.INSTT_ID
)
WHERE (M.CXFC IS NULL OR TRIM(M.CXFC) = '')
  AND EXISTS (
      SELECT 1
      FROM COMTNINSTTINFO I
      WHERE I.INSTT_ID = M.INSTT_ID
        AND I.REPRSNT_NM IS NOT NULL
        AND TRIM(I.REPRSNT_NM) <> ''
  );

UPDATE COMTNENTRPRSMBER M
SET ZIP = (
    SELECT I.ZIP
    FROM COMTNINSTTINFO I
    WHERE I.INSTT_ID = M.INSTT_ID
)
WHERE (M.ZIP IS NULL OR TRIM(M.ZIP) = '' OR TRIM(M.ZIP) = '000000')
  AND EXISTS (
      SELECT 1
      FROM COMTNINSTTINFO I
      WHERE I.INSTT_ID = M.INSTT_ID
        AND I.ZIP IS NOT NULL
        AND TRIM(I.ZIP) <> ''
  );

UPDATE COMTNENTRPRSMBER M
SET ADRES = (
    SELECT I.ADRES
    FROM COMTNINSTTINFO I
    WHERE I.INSTT_ID = M.INSTT_ID
)
WHERE (M.ADRES IS NULL OR TRIM(M.ADRES) = '' OR TRIM(M.ADRES) = '주소미입력')
  AND EXISTS (
      SELECT 1
      FROM COMTNINSTTINFO I
      WHERE I.INSTT_ID = M.INSTT_ID
        AND I.ADRES IS NOT NULL
        AND TRIM(I.ADRES) <> ''
  );

UPDATE COMTNENTRPRSMBER M
SET DETAIL_ADRES = (
    SELECT I.DETAIL_ADRES
    FROM COMTNINSTTINFO I
    WHERE I.INSTT_ID = M.INSTT_ID
)
WHERE (M.DETAIL_ADRES IS NULL OR TRIM(M.DETAIL_ADRES) = '')
  AND EXISTS (
      SELECT 1
      FROM COMTNINSTTINFO I
      WHERE I.INSTT_ID = M.INSTT_ID
        AND I.DETAIL_ADRES IS NOT NULL
        AND TRIM(I.DETAIL_ADRES) <> ''
  );

UPDATE COMTNENTRPRSMBER M
SET APPLCNT_EMAIL_ADRES = (
    SELECT I.CHARGER_EMAIL
    FROM COMTNINSTTINFO I
    WHERE I.INSTT_ID = M.INSTT_ID
)
WHERE (M.APPLCNT_EMAIL_ADRES IS NULL OR TRIM(M.APPLCNT_EMAIL_ADRES) = '')
  AND EXISTS (
      SELECT 1
      FROM COMTNINSTTINFO I
      WHERE I.INSTT_ID = M.INSTT_ID
        AND I.CHARGER_EMAIL IS NOT NULL
        AND TRIM(I.CHARGER_EMAIL) <> ''
  );
