CREATE CLASS COMTNENTRPRSMBERFILE (
    FILE_ID VARCHAR(60) NOT NULL,
    ENTRPRS_MBER_ID VARCHAR(20) NOT NULL,
    FILE_SN INTEGER NOT NULL,
    STRE_FILE_NM VARCHAR(255) NOT NULL,
    ORIGNL_FILE_NM VARCHAR(255),
    FILE_STRE_PATH VARCHAR(500) NOT NULL,
    FILE_MG BIGINT,
    FILE_EXTSN VARCHAR(20),
    FILE_CN VARCHAR(200),
    REGIST_PNTTM DATETIME DEFAULT SYSDATETIME
);

ALTER CLASS COMTNENTRPRSMBERFILE ADD CONSTRAINT PK_COMTNENTRPRSMBERFILE PRIMARY KEY (FILE_ID);

CREATE INDEX IDX_COMTNENTRPRSMBERFILE_01 ON COMTNENTRPRSMBERFILE (ENTRPRS_MBER_ID);
