CREATE CLASS COMTNINSTTFILE (
    FILE_ID VARCHAR(60) NOT NULL,
    INSTT_ID VARCHAR(20) NOT NULL,
    FILE_SN INTEGER NOT NULL,
    STRE_FILE_NM VARCHAR(255) NOT NULL,
    ORIGNL_FILE_NM VARCHAR(255),
    FILE_STRE_PATH VARCHAR(500) NOT NULL,
    FILE_MG BIGINT,
    FILE_EXTSN VARCHAR(20),
    FILE_CN VARCHAR(200),
    REGIST_PNTTM DATETIME DEFAULT SYSDATETIME
);

ALTER CLASS COMTNINSTTFILE ADD CONSTRAINT PK_COMTNINSTTFILE PRIMARY KEY (FILE_ID);

CREATE INDEX IDX_COMTNINSTTFILE_01 ON COMTNINSTTFILE (INSTT_ID);
