-- CUBRID용 MSA SQL (msa_cubrid.sql)
-- MySQL에서 CUBRID로 변환

-- MSATNAUTHORGROUPINFO
CREATE TABLE MSATNAUTHORGROUPINFO (
    GROUP_ID              CHAR(20) NOT NULL,
    GROUP_NM              VARCHAR(60) NOT NULL,
    GROUP_CREAT_DE        CHAR(20) NOT NULL,
    GROUP_DC              VARCHAR(100) NULL,
    PRIMARY KEY (GROUP_ID)
);

CREATE UNIQUE INDEX MSATNAUTHORGROUPINFO_PK ON MSATNAUTHORGROUPINFO (GROUP_ID);

-- MSATNAUTHORINFO
CREATE TABLE MSATNAUTHORINFO (
    AUTHOR_CODE           VARCHAR(30) NOT NULL,
    AUTHOR_NM             VARCHAR(60) NOT NULL,
    AUTHOR_DC             VARCHAR(200) NULL,
    AUTHOR_CREAT_DE       CHAR(20) NOT NULL,
    PRIMARY KEY (AUTHOR_CODE)
);

CREATE UNIQUE INDEX MSATNAUTHORINFO_PK ON MSATNAUTHORINFO (AUTHOR_CODE);

-- MSATNROLEINFO
CREATE TABLE MSATNROLEINFO (
    ROLE_CODE             VARCHAR(50) NOT NULL,
    ROLE_NM               VARCHAR(60) NOT NULL,
    ROLE_PTTRN            VARCHAR(300) NULL,
    ROLE_DC               VARCHAR(200) NULL,
    ROLE_TY               VARCHAR(80) NULL,
    ROLE_SORT             VARCHAR(10) NULL,
    ROLE_CREAT_DE         CHAR(20) NOT NULL,
    PRIMARY KEY (ROLE_CODE)
);

CREATE UNIQUE INDEX MSATNROLEINFO_PK ON MSATNROLEINFO (ROLE_CODE);

-- MSATNAUTHORROLERELATE (FK는 나중에 추가)
CREATE TABLE MSATNAUTHORROLERELATE (
    AUTHOR_CODE           VARCHAR(30) NOT NULL,
    ROLE_CODE             VARCHAR(50) NOT NULL,
    CREAT_DT              DATETIME NULL,
    PRIMARY KEY (AUTHOR_CODE,ROLE_CODE)
);

CREATE UNIQUE INDEX MSATNAUTHORROLERELATE_PK ON MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE);
CREATE INDEX MSATNAUTHORROLERELATE_i01 ON MSATNAUTHORROLERELATE (AUTHOR_CODE);
CREATE INDEX MSATNAUTHORROLERELATE_i02 ON MSATNAUTHORROLERELATE (ROLE_CODE);

-- FK 추가
ALTER TABLE MSATNAUTHORROLERELATE ADD CONSTRAINT MSATNAUTHORROLERELATE_FK1 FOREIGN KEY (AUTHOR_CODE) REFERENCES MSATNAUTHORINFO(AUTHOR_CODE) ON DELETE CASCADE;
ALTER TABLE MSATNAUTHORROLERELATE ADD CONSTRAINT MSATNAUTHORROLERELATE_FK2 FOREIGN KEY (ROLE_CODE) REFERENCES MSATNROLEINFO(ROLE_CODE) ON DELETE CASCADE;

-- MSATNROLES_HIERARCHY (FK는 나중에 추가)
CREATE TABLE MSATNROLES_HIERARCHY (
    PARNTS_ROLE           VARCHAR(30) NOT NULL,
    CHLDRN_ROLE           VARCHAR(30) NOT NULL,
    PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE)
);

CREATE UNIQUE INDEX MSATNROLES_HIERARCHY_PK ON MSATNROLES_HIERARCHY (PARNTS_ROLE, CHLDRN_ROLE);
CREATE INDEX MSATNROLES_HIERARCHY_i01 ON MSATNROLES_HIERARCHY (PARNTS_ROLE);
CREATE INDEX MSATNROLES_HIERARCHY_i02 ON MSATNROLES_HIERARCHY (CHLDRN_ROLE);

-- FK 추가
ALTER TABLE MSATNROLES_HIERARCHY ADD CONSTRAINT MSATNROLES_HIERARCHY_FK1 FOREIGN KEY (PARNTS_ROLE) REFERENCES MSATNAUTHORINFO(AUTHOR_CODE) ON DELETE CASCADE;
ALTER TABLE MSATNROLES_HIERARCHY ADD CONSTRAINT MSATNROLES_HIERARCHY_FK2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES MSATNAUTHORINFO(AUTHOR_CODE) ON DELETE CASCADE;

-- MSATNEMPLYRSCRTYESTBS
CREATE TABLE MSATNEMPLYRSCRTYESTBS (
    SCRTY_DTRMN_TRGET_ID  VARCHAR(20) NOT NULL,
    MBER_TY_CODE          CHAR(5) NULL,
    AUTHOR_CODE           VARCHAR(30) NOT NULL,
    PRIMARY KEY (SCRTY_DTRMN_TRGET_ID)
);

CREATE UNIQUE INDEX MSATNEMPLYRSCRTYESTBS_PK ON MSATNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID);
CREATE INDEX MSATNEMPLYRSCRTYESTBS_i04 ON MSATNEMPLYRSCRTYESTBS (AUTHOR_CODE);

-- MSATNMENUCREATDTLS (FK는 나중에 추가)
CREATE TABLE MSATNMENUCREATDTLS (
    MENU_NO               NUMERIC(20) NOT NULL,
    AUTHOR_CODE           VARCHAR(30) NOT NULL,
    MAPNG_CREAT_ID        VARCHAR(30) NULL,
    PRIMARY KEY (MENU_NO,AUTHOR_CODE)
);

CREATE UNIQUE INDEX MSATNMENUCREATDTLS_PK ON MSATNMENUCREATDTLS (MENU_NO, AUTHOR_CODE);
CREATE INDEX MSATNMENUCREATDTLS_i02 ON MSATNMENUCREATDTLS (MENU_NO);
CREATE INDEX MSATNMENUCREATDTLS_i03 ON MSATNMENUCREATDTLS (MAPNG_CREAT_ID);
CREATE INDEX MSATNMENUCREATDTLS_i04 ON MSATNMENUCREATDTLS (AUTHOR_CODE);

-- FK 추가
ALTER TABLE MSATNMENUCREATDTLS ADD CONSTRAINT MSATNMENUCREATDTLS_FK1 FOREIGN KEY (AUTHOR_CODE) REFERENCES MSATNAUTHORINFO(AUTHOR_CODE);

-- INSERT 문 (SYSDATE -> SYSDATE로 동일)
-- 그룹
INSERT INTO MSATNAUTHORGROUPINFO (GROUP_ID, GROUP_NM, GROUP_CREAT_DE, GROUP_DC) VALUES ('GROUP_00000000000000', '0번  그룹입니다', SYSDATE, '0번  그룹입니다');

-- 권한정보
INSERT INTO MSATNAUTHORINFO VALUES ('ROLE_ANONYMOUS', '모든 사용자', '', SYSDATE);
INSERT INTO MSATNAUTHORINFO VALUES ('IS_AUTHENTICATED_ANONYMOUSLY', '스프링시큐리티 내부사용(롤부여 금지)', '', SYSDATE);
INSERT INTO MSATNAUTHORINFO VALUES ('IS_AUTHENTICATED_REMEMBERED', '스프링시큐리티 내부사용(롤부여 금지)', '', SYSDATE);
INSERT INTO MSATNAUTHORINFO VALUES ('IS_AUTHENTICATED_FULLY', '스프링시큐리티 내부사용(롤부여 금지)', '', SYSDATE);
INSERT INTO MSATNAUTHORINFO VALUES ('ROLE_USER', '일반 사용자', '', SYSDATE);
INSERT INTO MSATNAUTHORINFO VALUES ('ROLE_ADMIN', '관리자', '', SYSDATE);

-- 롤 등록
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000001', '로그인', '/uat/uia/**', '로그인', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000002', '로그인정책관리', '/uat/uap/**', '로그인정책관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000003', '권한관리', '/sec/ram/**', '권한관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000004', '권한그룹관리', '/sec/rgm/**', '권한그룹관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000005', '그룹관리', '/sec/gmt/**', '그룹관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000006', '롤관리', '/sec/rmt/**', '롤관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000007', '모바일신분증', '/mip/**', '모바일신분증', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000008', '블로그관리', '/cop/bls/**', '블로그관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000009', '게시판관리', '/cop/bbs/**', '게시판관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000010', '게시글관리', '/cop/brd/**', '게시글관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000011', '커뮤니티관리', '/cop/cmy/**', '커뮤니티관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000012', '설문관리', '/uss/olp/qmc/**', '설문관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000013', '설문조사', '/uss/olp/qri/**', '설문조사', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000014', '설문템플릿관리', '/uss/olp/qtm/**', '설문템플릿관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000015', '응답자관리', '/uss/olp/qrm/**', '응답자관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000016', '질문관리', '/uss/olp/qqm/**', '질문관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000017', '항목관리', '/uss/olp/qim/**', '항목관리', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000018', '공통분류코드', '/sym/ccm/ccc/**', '공통분류코드', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000019', '공통상세코드', '/sym/ccm/cde/**', '공통상세코드', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000020', '공통코드', '/sym/ccm/cca/**', '공통코드', 'url', '1', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000021', '검색엔진', '/ext/ops/**', '검색엔진', 'url', '1', SYSDATE);

-- 권한 롤 매핑
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ANONYMOUS', 'web-000001', SYSDATE);
INSERT INTO MSATNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES ('web-000022', '관리자메인', '/adminmain/**', '관리자메인', 'url', '1', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000022', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000002', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000003', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000004', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000005', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000006', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000007', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000008', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000009', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000010', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000011', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000012', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000013', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000014', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000015', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000016', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000017', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000018', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000019', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ADMIN', 'web-000020', SYSDATE);
INSERT INTO MSATNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_USER', 'web-000021', SYSDATE);

-- 롤 계층구조
INSERT INTO MSATNROLES_HIERARCHY VALUES ('ROLE_ANONYMOUS', 'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO MSATNROLES_HIERARCHY VALUES ('IS_AUTHENTICATED_ANONYMOUSLY', 'IS_AUTHENTICATED_REMEMBERED');
INSERT INTO MSATNROLES_HIERARCHY VALUES ('IS_AUTHENTICATED_REMEMBERED', 'IS_AUTHENTICATED_FULLY');
INSERT INTO MSATNROLES_HIERARCHY VALUES ('IS_AUTHENTICATED_FULLY', 'ROLE_USER');
INSERT INTO MSATNROLES_HIERARCHY VALUES ('ROLE_USER', 'ROLE_ADMIN');

-- 사용자보안설정
INSERT INTO MSATNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE) VALUES ('USRCNFRM_00000000000', 'USR03', 'ROLE_ADMIN');
INSERT INTO MSATNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE) VALUES ('USRCNFRM_00000000001', 'USR01', 'ROLE_USER');
INSERT INTO MSATNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE) VALUES ('USRCNFRM_00000000002', 'USR02', 'ROLE_USER');
INSERT INTO MSATNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE) VALUES ('USRCNFRM_99999999999', 'USR03', 'ROLE_ADMIN');

-- COMMENT 추가 (CUBRID에서는 컬럼 COMMENT가 CREATE TABLE에서만 지원됨)
-- 테이블 코멘트만 지원
ALTER TABLE MSATNAUTHORGROUPINFO COMMENT = '권한그룹정보';
ALTER TABLE MSATNAUTHORINFO COMMENT = '권한정보';
ALTER TABLE MSATNAUTHORROLERELATE COMMENT = '권한롤관계';
ALTER TABLE MSATNROLEINFO COMMENT = '롤정보';
ALTER TABLE MSATNROLES_HIERARCHY COMMENT = '롤 계층구조';
ALTER TABLE MSATNEMPLYRSCRTYESTBS COMMENT = '사용자보안설정';
ALTER TABLE MSATNMENUCREATDTLS COMMENT = '메뉴생성내역';

-- 컬럼 코멘트는 CREATE TABLE에서만 지원되므로 별도 처리 필요
